#! /usr/bin/env python3
"""Molly guard control CLI."""

from argparse import ArgumentParser

from smollyguardl import CONFIG, load_config, reboot, start, stop


def get_args():
    """Returns the command line arguments."""

    parser = ArgumentParser(description='Molly guard control CLI.')
    subparsers = parser.add_subparsers(dest='action')
    start_parser = subparsers.add_parser('start', help='start mollyguarding')
    start_parser.add_argument('unit', nargs='*', help='a list of units to mask')
    stop_parser = subparsers.add_parser('stop', help='stop mollyguarding')
    stop_parser.add_argument('unit', nargs='*', help='a list of units to mask')
    reboot_parser = subparsers.add_parser(
        'reboot', help='safely reboot the system')
    reboot_parser.add_argument(
        '-n', '--no-ask-hostname', action='store_true',
        help='do not ask the host name before rebooting')
    return parser.parse_args()


def main():
    """Runs the main program."""

    args = get_args()
    load_config()

    if args.mode == 'start':
        return start(args.unit)

    if args.mode == 'stop':
        return stop(args.unit)

    if args.mode == 'reboot':
        return reboot(ask_hostname=not args.no_ask_host_name)

    return None


if __name__ == '__main__':
    main()
